In [7]:
import torch

In [8]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.shape

torch.Size([12])

In [10]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.tensor([[2, 1, 4, 2], [1, 2, 3, 4], [3, 1, 2, 4]]).shape

torch.Size([3, 4])

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]))

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
(torch.cat((X, Y), dim=0)).shape, torch.cat((X, Y), dim=1)

(torch.Size([6, 4]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
X.sum()

tensor(66.)

In [17]:
# broadcasting mechanism
a = torch.arange(4).reshape((4, 1))
b = torch.arange(3).reshape((1, 3))
a, b

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1, 2]]))

In [18]:
a + b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [19]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [20]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [25]:
Y

tensor([[38., 37., 40., 39.],
        [37., 38., 39., 40.],
        [28., 30., 32., 34.]])

In [26]:
before

140492116484160

In [27]:
id(Y)

140492116487200

In [28]:
Y[:] = X + Y
id(Y)

140492116487200

In [29]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [30]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)