In [16]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [17]:
x.requires_grad_(True) # 等价于 x = torch.arange(4.0, requires_grad=True)
x.grad # 默认值是none

In [18]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [19]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [25]:
# 默认情况下，pytorch会累积梯度，需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [27]:
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x))
# y.sum().backward()
y.backward(torch.ones(len(x)))
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), tensor([0., 2., 4., 6.]))

In [29]:
# 将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [30]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [33]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a, a.grad, d, a.grad == d/a

(tensor(1.3500, requires_grad=True),
 tensor(1024.),
 tensor(1382.3618, grad_fn=<MulBackward0>),
 tensor(True))