In [6]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [33]:
# 将向量视为标量值组成的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [34]:
# 通过张量的索引来访问任一元素
x[3]

tensor(3)

In [35]:
# 访问张量的长度
len(x)

4

In [36]:
# 只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [37]:
# 通过指定两个分量m和n创建一个形状为mxn的矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [38]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [39]:
# 对称矩阵（symmetric matrix）A=A.T
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [40]:
# 向量是标量的推广，矩阵是向量的推广，构建具有多轴的数据结构
X = torch.arange(24).reshape(2,3,4)

In [41]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [42]:
# 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [43]:
# 两个矩阵按元素乘法称为hadamard product
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [44]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [45]:
A = torch.arange(20*2).reshape(2, 5, 4)
A.shape, A.sum(), A

(torch.Size([2, 5, 4]),
 tensor(780),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]))

In [46]:
# 指定求和汇总张量的轴
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [47]:
print(A.sum(axis=[0, 2]))
A

tensor([ 92, 124, 156, 188, 220])


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [48]:
# 计算总和活均值时保持轴数不变
sum_A = A.sum(axis=1, keepdims=True)
sum_A.shape

torch.Size([2, 1, 4])

In [49]:
# 通过广播将A除以sum_A
A / sum_A
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [50]:
# 某个轴计算A元素的累积总和
A.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

In [52]:
# 点积是相同位置的按元素乘积的和
y = torch.ones(4, dtype=torch.float32)
x = torch.arange(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [57]:
# 矩阵向量Ax是一个长度为m的列向量，其ith元素是点积aiTx, mv -- matrix-vector
A = torch.arange(20).reshape(5, 4).float()
A.shape, x.shape, A, x, torch.mv(A, x)

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [60]:
# mm -- matrix-matrix
B = torch.ones(4, 3)
torch.mm(A, B), B.dtype

(tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 torch.float32)

In [61]:
# L2范数是向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [62]:
# 矩阵的弗罗贝尼乌斯 Frobenius norm 是矩阵元素的平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)